// <auto-generated />
namespace IzinTakipApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddSirketPolitikasi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSirketPolitikasi));
        
        string IMigrationMetadata.Id
        {
            get { return "202607210744531_AddSirketPolitikasi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
